// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_pLasRRYRm5ZTqxq4ojTqVlpBHuaDqQ',
    appId: '1:519494394961:web:97bc56dac69c7d1cb7c470',
    messagingSenderId: '519494394961',
    projectId: 'bmi-user-firebase',
    authDomain: 'bmi-user-firebase.firebaseapp.com',
    storageBucket: 'bmi-user-firebase.firebasestorage.app',
    measurementId: 'G-KPPVT0PQMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfbvCZMpGmGcPVDFcHcT3WLfncnqbytzc',
    appId: '1:519494394961:android:ffca9393cd0a57a8b7c470',
    messagingSenderId: '519494394961',
    projectId: 'bmi-user-firebase',
    storageBucket: 'bmi-user-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBia7dDK_1OFlrLRBQnihtq6x-GHgWnhjE',
    appId: '1:519494394961:ios:3a3c7d9042b1ebb2b7c470',
    messagingSenderId: '519494394961',
    projectId: 'bmi-user-firebase',
    storageBucket: 'bmi-user-firebase.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBia7dDK_1OFlrLRBQnihtq6x-GHgWnhjE',
    appId: '1:519494394961:ios:3a3c7d9042b1ebb2b7c470',
    messagingSenderId: '519494394961',
    projectId: 'bmi-user-firebase',
    storageBucket: 'bmi-user-firebase.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_pLasRRYRm5ZTqxq4ojTqVlpBHuaDqQ',
    appId: '1:519494394961:web:15c24f6d8cf4aa48b7c470',
    messagingSenderId: '519494394961',
    projectId: 'bmi-user-firebase',
    authDomain: 'bmi-user-firebase.firebaseapp.com',
    storageBucket: 'bmi-user-firebase.firebasestorage.app',
    measurementId: 'G-F89P5GB65Y',
  );
}
